// @ts-nocheck
// GENERATED by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async buildInfo() : Promise<BuildInfo> {
    return await TAURI_INVOKE("build_info");
},
/**
 * Returns the current log file contents ("" when it does not exist yet).
 */
async readLog() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Truncates the log file in place so the logger's open handle stays valid.
 */
async clearLog() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens the log directory in the OS file manager.
 */
async openLogsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_logs_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: Settings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRepo(path: string) : Promise<Result<RepoInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_repo", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeRepo(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_repo", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLog(repoId: string, skip: number, limit: number) : Promise<Result<LogPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log", { repoId, skip, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStatus(repoId: string) : Promise<Result<WorkingStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_status", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBranches(repoId: string) : Promise<Result<BranchList, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branches", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTags(repoId: string) : Promise<Result<TagInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tags", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listStashes(repoId: string) : Promise<Result<StashInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_stashes", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileDiff(repoId: string, path: string, source: DiffSource) : Promise<Result<FileDiff, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_diff", { repoId, path, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCommitDetail(repoId: string, sha: string) : Promise<Result<CommitDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_commit_detail", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stageFile(repoId: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stage_file", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unstageFile(repoId: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unstage_file", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stageAll(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stage_all", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unstageAll(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unstage_all", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardFile(repoId: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_file", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCommit(repoId: string, summary: string, description: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_commit", { repoId, summary, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkoutBranch(repoId: string, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("checkout_branch", { repoId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createBranch(repoId: string, name: string, checkout: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_branch", { repoId, name, checkout }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stashSave(repoId: string, message: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stash_save", { repoId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stashPop(repoId: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stash_pop", { repoId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitFetch(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_fetch", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPull(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_pull", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPush(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_push", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitClone(url: string, destination: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_clone", { url, destination }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanCodeFolder(folder: string) : Promise<Result<ScannedRepo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_code_folder", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiGetCatalog() : Promise<Result<CatalogProvider[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_get_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiListConfigured() : Promise<Result<AiProviderStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_list_configured") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiSetApiKey(provider: string, key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_set_api_key", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiRemoveProvider(provider: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_remove_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiCopilotDeviceStart() : Promise<Result<DeviceCodeInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_copilot_device_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One poll pass; the frontend loops on Pending so sign-in stays cancellable.
 */
async aiCopilotDevicePoll(deviceCode: string, interval: number) : Promise<Result<PollResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_copilot_device_poll", { deviceCode, interval }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateCommitMessage(repoId: string, provider: string, model: string) : Promise<Result<GeneratedCommitMessage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_commit_message", { repoId, provider, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiProviderStatus = { id: string; configured: boolean }
export type BranchInfo = { name: string; is_head: boolean; upstream: string | null; ahead: number; behind: number }
export type BranchList = { local: BranchInfo[]; remote: string[] }
export type BuildInfo = { version: string; build_date: string; git_hash: string; debug: boolean }
export type CatalogModel = { id: string; name: string }
export type CatalogProvider = { id: string; name: string; base_url: string; dialect: Dialect; models: CatalogModel[] }
export type CommitDetail = { sha: string; summary: string; body: string; author_name: string; author_email: string; time: number; parent_shas: string[]; files: FileChange[] }
export type CommitEntry = { sha: string; short_sha: string; summary: string; author_name: string; author_email: string; author_initials: string; 
/**
 * Unix epoch seconds.
 */
time: number; lane: number; 
/**
 * Lane of each parent edge, aligned with `parent_shas`.
 */
parent_lanes: number[]; parent_shas: string[]; is_merge: boolean; refs: RefInfo[] }
export type DeviceCodeInfo = { device_code: string; user_code: string; verification_uri: string; 
/**
 * Minimum seconds between polls.
 */
interval: number }
export type Dialect = "anthropic" | "open_ai"
export type DiffLineEntry = { 
/**
 * "+" added, "-" removed, "" context, "@" hunk header.
 */
sign: string; old_no: number | null; new_no: number | null; text: string }
export type DiffSource = { kind: "staged" } | { kind: "unstaged" } | { kind: "commit"; sha: string }
export type FileChange = { path: string; status: StatusCode; additions: number; deletions: number; conflicted: boolean }
export type FileDiff = { path: string; additions: number; deletions: number; lines: DiffLineEntry[]; binary: boolean }
export type GeneratedCommitMessage = { summary: string; description: string }
export type GitProgressPayload = { repo_id: string; operation: string; line: string }
export type LogPage = { commits: CommitEntry[]; has_more: boolean }
export type PollResult = 
/**
 * Token acquired and saved; sign-in is complete.
 */
{ status: "complete" } | 
/**
 * User has not finished authorizing yet; poll again after `interval`.
 */
{ status: "pending"; interval: number }
export type RecentRepo = { name: string; path: string }
export type RefInfo = { name: string; type: RefKind }
export type RefKind = "head" | "branch" | "remote" | "tag"
export type RepoChangedPayload = { repo_id: string }
export type RepoInfo = { id: string; name: string; path: string; head_branch: string | null }
export type ScannedRepo = { name: string; path: string; 
/**
 * Current branch parsed from .git/HEAD as text (None when detached/unreadable).
 */
head_branch: string | null }
export type Settings = { 
/**
 * Paths of repos open in tabs, in tab order, so they can be reopened on launch.
 */
open_repos?: string[]; 
/**
 * Id of the repo that was active when the app last closed.
 */
active_repo_path?: string | null; recents?: RecentRepo[]; code_folder?: string | null; clone_directory?: string | null; update_channel?: UpdateChannel; ai_provider?: string | null; ai_model?: string | null }
export type StashInfo = { index: number; message: string }
export type StatusCode = "A" | "M" | "D" | "R" | "!"
export type TagInfo = { name: string }
export type UpdateChannel = "stable" | "beta"
export type WorkingStatus = { staged: FileChange[]; unstaged: FileChange[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
