// @ts-nocheck
// GENERATED by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async buildInfo() : Promise<BuildInfo> {
    return await TAURI_INVOKE("build_info");
},
/**
 * Returns the current log file contents ("" when it does not exist yet).
 */
async readLog() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Truncates the log file in place so the logger's open handle stays valid.
 */
async clearLog() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens the log directory in the OS file manager.
 */
async openLogsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_logs_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the repo folder in the OS file manager (Explorer / Finder / xdg).
 */
async revealInFileManager(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reveal_in_file_manager", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open the repo in VS Code via its `code` launcher. Requires `code` on PATH
 * (VS Code's "Shell Command: Install 'code' command in PATH").
 */
async openInEditor(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_editor", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a terminal in the repo folder. Uses Windows Terminal if present,
 * falling back to the classic console; a native terminal elsewhere.
 */
async openInTerminal(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_in_terminal", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: Settings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRepo(path: string) : Promise<Result<RepoInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_repo", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeRepo(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_repo", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRepoIcon(repoPath: string) : Promise<Result<RepoIcon | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_repo_icon", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async findRepoIcons(repoPath: string) : Promise<Result<RepoIcon[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_repo_icons", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setRepoIcon(repoPath: string, sourcePath: string) : Promise<Result<RepoIcon, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_repo_icon", { repoPath, sourcePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearRepoIcon(repoPath: string) : Promise<Result<RepoIcon | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_repo_icon", { repoPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLog(repoId: string, skip: number, limit: number) : Promise<Result<LogPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log", { repoId, skip, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStatus(repoId: string) : Promise<Result<WorkingStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_status", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBranches(repoId: string) : Promise<Result<BranchList, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branches", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Ahead/behind counts between two arbitrary refs (branch, remote branch, tag,
 * or sha). `ahead` = commits `ours` has that `theirs` doesn't; `behind` = the
 * reverse. Backs the drag-to-sync analysis for non-tracking branch pairs.
 */
async branchRelation(repoId: string, ours: string, theirs: string) : Promise<Result<BranchRelation, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("branch_relation", { repoId, ours, theirs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTags(repoId: string) : Promise<Result<TagInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tags", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listStashes(repoId: string) : Promise<Result<StashInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_stashes", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileDiff(repoId: string, path: string, source: DiffSource) : Promise<Result<FileDiff, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_diff", { repoId, path, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCommitDetail(repoId: string, sha: string) : Promise<Result<CommitDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_commit_detail", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stageFile(repoId: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stage_file", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stage an exact set of files as one visible folder action.
 */
async stageFiles(repoId: string, paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stage_files", { repoId, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unstageFile(repoId: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unstage_file", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unstage an exact set of files as one visible folder action.
 */
async unstageFiles(repoId: string, paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unstage_files", { repoId, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stageAll(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stage_all", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unstageAll(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unstage_all", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardFile(repoId: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_file", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Discard staged and unstaged changes for an exact set of files. The caller
 * confirms this destructive action before invoking it.
 */
async discardFiles(repoId: string, paths: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_files", { repoId, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Discard every uncommitted change: unstage the index, restore all tracked
 * files to HEAD, and remove untracked files. Irreversible; the caller confirms.
 */
async discardAll(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_all", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add one pattern to the repository's .gitignore.
 */
async addToGitignore(repoId: string, pattern: string) : Promise<Result<IgnoreOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_to_gitignore", { repoId, pattern }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCommit(repoId: string, summary: string, description: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_commit", { repoId, summary, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkoutBranch(repoId: string, name: string, mode: BranchSwitchMode) : Promise<Result<CheckoutOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("checkout_branch", { repoId, name, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a branch. `sha` names the commit to branch from; empty means the
 * current HEAD. When `checkout` is set, HEAD moves onto the new branch.
 */
async createBranch(repoId: string, name: string, sha: string, checkout: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_branch", { repoId, name, sha, checkout }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a local branch. Refuses to delete the branch HEAD is on.
 */
async deleteBranch(repoId: string, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_branch", { repoId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a local branch. Safe on the branch you are currently on, unlike
 * delete: git moves HEAD along with the ref. The upstream link is preserved,
 * so a renamed branch still pushes where it did before.
 */
async renameBranch(repoId: string, name: string, newName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_branch", { repoId, name, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a tag. `sha` is the commit to tag (empty = current HEAD). When
 * `message` is non-empty the tag is annotated (carries author + message);
 * otherwise it is a lightweight tag pointing straight at the commit.
 */
async createTag(repoId: string, name: string, sha: string, message: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_tag", { repoId, name, sha, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a tag by name.
 */
async deleteTag(repoId: string, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_tag", { repoId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset the current branch to a commit. Hard reset discards uncommitted work,
 * so it is refused over a dirty tree. Returns where the branch pointed before
 * the reset, so the caller can offer an undo. Soft/Mixed keep the working tree.
 */
async resetCurrent(repoId: string, sha: string, mode: ResetMode) : Promise<Result<RefMove, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_current", { repoId, sha, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move the current branch ref to a commit without touching the working tree
 * (like `git branch -f <current> <sha>` re-pointing HEAD's branch). Refused
 * over a dirty tree so the tree never silently diverges from the new tip.
 */
async moveCurrentBranch(repoId: string, sha: string) : Promise<Result<RefMove, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_current_branch", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check out a commit directly, leaving HEAD detached (not on any branch).
 * Refused over a dirty tree so no uncommitted work is clobbered. The frontend
 * warns that new commits here won't belong to a branch until one is made.
 */
async checkoutCommit(repoId: string, sha: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("checkout_commit", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reword a commit's message. Only the tip commit (HEAD) is supported: it is
 * amended in place, keeping its tree, parent, and original author. Rewording
 * an older commit would rewrite history below it (a rebase) and is refused.
 */
async rewordCommit(repoId: string, sha: string, message: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reword_commit", { repoId, sha, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Revert a commit: apply the inverse of its changes as a new commit on top of
 * HEAD, so history is preserved. A clean revert commits immediately and
 * returns no conflicts. A conflicting revert leaves REVERT_HEAD and the
 * conflicted index for the shared conflict flow to resolve and finish.
 */
async revertCommit(repoId: string, sha: string) : Promise<Result<MergeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("revert_commit", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drop a commit from the current branch: replay every commit after it onto its
 * parent, removing just that one. Only works on a clean linear stretch (no
 * merge commits above the target). A conflict during replay aborts the whole
 * operation and restores the branch, so the branch is never left half-rebased.
 */
async dropCommit(repoId: string, sha: string) : Promise<Result<RefMove, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("drop_commit", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * True when the repo has at least one linked worktree. Backs the auto-enable
 * of the worktree feature so users who already work with worktrees see the UI.
 */
async hasWorktrees(repoId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_worktrees", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve the origin remote's web URL for a commit, or None when it can't be
 * built (no origin, unknown host) or the commit isn't on any remote-tracking
 * branch yet (so the link would 404). Supports GitHub, GitLab, Bitbucket.
 */
async commitWebUrl(repoId: string, sha: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_web_url", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stashSave(repoId: string, message: string | null) : Promise<Result<StashOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stash_save", { repoId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stashPop(repoId: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stash_pop", { repoId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apply a stash to the working tree while keeping it in the stash list.
 */
async stashApply(repoId: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stash_apply", { repoId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a stash without touching the working tree.
 */
async stashDrop(repoId: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stash_drop", { repoId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Every submodule whose checked-out commit differs from the commit the parent
 * repo pins (plus uninitialized ones). Empty when all submodules are in sync.
 */
async listSubmodules(repoId: string) : Promise<Result<SubmoduleMove[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_submodules", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Snap a submodule back to the commit the parent repo records -- the submodule
 * equivalent of discarding changes. `init` also checks out an uninitialized
 * submodule for the first time. The recorded commit is fetched only if it is
 * not already present locally.
 */
async updateSubmodule(repoId: string, path: string, init: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_submodule", { repoId, path, init }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitFetch(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_fetch", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPull(repoId: string) : Promise<Result<PullResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_pull", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPush(repoId: string) : Promise<Result<PushResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_push", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push a named local branch, which need not be the one checked out. A branch
 * with no upstream is published to the default remote and tracked from then
 * on, so the next push needs no extra decision.
 */
async gitPushBranch(repoId: string, branch: string) : Promise<Result<PushResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_push_branch", { repoId, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Bring a branch up to date with its upstream without checking it out.
 * 
 * A branch that is only behind fast-forwards cleanly. One that has also moved
 * locally cannot: combining the two histories is a merge, which needs a
 * working tree, so this reports that rather than guessing. Pulling the branch
 * you are on goes through `git_pull` instead.
 */
async gitPullBranch(repoId: string, branch: string) : Promise<Result<PullResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_pull_branch", { repoId, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Link a local branch to a remote branch of the same name, so push and pull
 * know where it belongs. Used to repair a branch whose remote branch was
 * deleted; publishing a brand-new branch happens through `git_push_branch`.
 */
async setBranchUpstream(repoId: string, branch: string, remote: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_branch_upstream", { repoId, branch, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push the current branch, overwriting the remote with `--force-with-lease`.
 * Lease-based so it refuses to clobber remote commits the user hasn't fetched;
 * used after a local rewind/rebase leaves the branch diverged from its upstream.
 */
async gitPushForce(repoId: string) : Promise<Result<PushResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_push_force", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rebase a branch onto `onto` (e.g. `origin/main`), replaying its commits on
 * top. Rebases the current branch when `branch` is None; otherwise git checks
 * out `branch` first and leaves HEAD there. A clean rebase returns no
 * conflicts. A rebase that hits conflicts leaves the repo paused
 * (rebase-in-progress) and returns the conflicted paths instead of erroring,
 * so the frontend can guide the user. Refuses to start over a dirty tree.
 */
async gitRebase(repoId: string, onto: string, branch: string | null) : Promise<Result<RebaseResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_rebase", { repoId, onto, branch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume a paused rebase after its conflicts were resolved and staged. The
 * next step may conflict again, in which case the returned paths are the new
 * round to resolve. `core.editor=true` keeps git from opening an editor for
 * the replayed commit messages.
 */
async rebaseContinue(repoId: string) : Promise<Result<RebaseResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebase_continue", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Abandon a paused rebase, restoring the branch to where it was before the
 * rebase started.
 */
async rebaseAbort(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebase_abort", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitClone(url: string, destination: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_clone", { url, destination }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List configured remotes with their URLs and remote-tracking branches.
 * Local config read only; no network.
 */
async listRemotes(repoId: string) : Promise<Result<RemoteInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_remotes", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tags the named remote already has. Hits the network via `git ls-remote`, so
 * callers should cache the result rather than polling it.
 */
async listRemoteTags(repoId: string, remote: string) : Promise<Result<RemoteTagInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_remote_tags", { repoId, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Local tags the remote is missing. `commit_on_remote` distinguishes tags that
 * can be pushed on their own from those whose commit hasn't been sent yet.
 */
async unpushedTags(repoId: string, remote: string) : Promise<Result<UnpushedTag[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unpushed_tags", { repoId, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Push one tag to a remote. Never force-updates: a tag the remote already has
 * under a different object fails rather than silently moving it.
 */
async pushTag(repoId: string, name: string, remote: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("push_tag", { repoId, name, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a tag from a remote. The local tag is left alone, so a tag can be
 * un-published without losing the local copy.
 */
async deleteRemoteTag(repoId: string, name: string, remote: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_remote_tag", { repoId, name, remote }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a new remote. Fails if the name is already in use.
 */
async addRemote(repoId: string, name: string, url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_remote", { repoId, name, url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a remote. Also rewrites its remote-tracking refs and any branch
 * upstreams that referenced the old name.
 */
async renameRemote(repoId: string, name: string, newName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_remote", { repoId, name, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change a remote's fetch URL.
 */
async setRemoteUrl(repoId: string, name: string, url: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_remote_url", { repoId, name, url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a remote and its remote-tracking branches.
 */
async removeRemote(repoId: string, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_remote", { repoId, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set a remote-tracking branch as the upstream ("set target") of the current
 * local branch. `remote_branch` is the full remote-tracking name, e.g.
 * `origin/main`.
 */
async setUpstream(repoId: string, remoteBranch: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_upstream", { repoId, remoteBranch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergeAnalysis(repoId: string, reference: string) : Promise<Result<MergeAnalysis, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_analysis", { repoId, reference }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergeBranch(repoId: string, reference: string) : Promise<Result<MergeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_branch", { repoId, reference }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Merge `source` into `target`, checking out `target` first when it isn't
 * already HEAD. Refuses to switch branches over a dirty tree so no work is
 * lost. This backs the direction modal's reverse ("merge current into other").
 */
async mergeDirectional(repoId: string, target: string, source: string) : Promise<Result<MergeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_directional", { repoId, target, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMergeState(repoId: string) : Promise<Result<MergeState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_merge_state", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async abortMerge(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_merge", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConflict(repoId: string, path: string) : Promise<Result<ConflictContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conflict", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveConflict(repoId: string, path: string, resolution: Resolution) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_conflict", { repoId, path, resolution }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async commitMerge(repoId: string, message: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_merge", { repoId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cherry-pick a commit onto the current branch. A clean apply commits
 * immediately (single-parent, keeping the original author) and returns no
 * conflicts. A conflicting apply leaves CHERRY_PICK_HEAD and the conflicted
 * index in place for the operation-aware conflict flow to resolve and finish.
 */
async cherryPick(repoId: string, sha: string) : Promise<Result<MergeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cherry_pick", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stageLines(repoId: string, path: string, selection: SelectedLine[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stage_lines", { repoId, path, selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unstageLines(repoId: string, path: string, selection: SelectedLine[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unstage_lines", { repoId, path, selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardLines(repoId: string, path: string, selection: SelectedLine[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_lines", { repoId, path, selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanCodeFolder(folder: string) : Promise<Result<ScannedRepo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_code_folder", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiGetCatalog() : Promise<Result<CatalogProvider[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_get_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiListConfigured() : Promise<Result<AiProviderStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_list_configured") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiSetApiKey(provider: string, key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_set_api_key", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiRemoveProvider(provider: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_remove_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The models the user can actually use for a provider. Asks the provider's
 * `/models` endpoint when a key is configured (so Copilot reflects plan
 * entitlements and other providers reflect key access), falling back to the
 * static catalog list.
 */
async aiListModels(provider: string) : Promise<Result<CatalogModel[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_list_models", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The built-in commit instruction, exposed so the settings UI can show it as
 * the placeholder and restore it with "Reset to default".
 */
async aiDefaultInstruction() : Promise<string> {
    return await TAURI_INVOKE("ai_default_instruction");
},
async aiCopilotDeviceStart() : Promise<Result<DeviceCodeInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_copilot_device_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One poll pass; the frontend loops on Pending so sign-in stays cancellable.
 */
async aiCopilotDevicePoll(deviceCode: string, interval: number) : Promise<Result<PollResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_copilot_device_poll", { deviceCode, interval }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateCommitMessage(repoId: string, provider: string, model: string) : Promise<Result<GeneratedCommitMessage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_commit_message", { repoId, provider, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateCommits(repoId: string, provider: string, model: string, commitCount: number, specialInstructions: string) : Promise<Result<AiCreatedCommit[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_commits", { repoId, provider, model, commitCount, specialInstructions }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubDeviceStart() : Promise<Result<DeviceCodeInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_device_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One poll pass; the frontend loops on Pending so sign-in stays cancellable.
 */
async githubDevicePoll(deviceCode: string, interval: number) : Promise<Result<PollResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_device_poll", { deviceCode, interval }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubSignOut() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_sign_out") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The signed-in login, or None when no token is stored or the token no
 * longer works (so the UI falls back to the connect prompt).
 */
async githubAuthStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_auth_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The GitHub owner/repo behind the origin remote, or None when origin is
 * missing or not hosted on github.com.
 */
async githubRepoSlug(repoId: string) : Promise<Result<GithubRepoRef | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_repo_slug", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubListPrs(owner: string, repo: string) : Promise<Result<PrSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_list_prs", { owner, repo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubListIssues(owner: string, repo: string) : Promise<Result<IssueSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_list_issues", { owner, repo }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubPrDetail(owner: string, repo: string, number: number) : Promise<Result<PrDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_pr_detail", { owner, repo, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubIssueDetail(owner: string, repo: string, number: number) : Promise<Result<IssueDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_issue_detail", { owner, repo, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Posts a comment on an issue or pull request (GitHub uses the issues
 * endpoint for both) and returns it for optimistic display.
 */
async githubComment(owner: string, repo: string, number: number, body: string) : Promise<Result<GithubComment, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_comment", { owner, repo, number, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubApprovePr(owner: string, repo: string, number: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_approve_pr", { owner, repo, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubMergePr(owner: string, repo: string, number: number, method: MergeMethod) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_merge_pr", { owner, repo, number, method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async githubCloseIssue(owner: string, repo: string, number: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("github_close_issue", { owner, repo, number }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiCreatedCommit = { sha: string; summary: string; description: string; files: string[] }
export type AiProviderStatus = { id: string; configured: boolean }
export type BranchInfo = { name: string; is_head: boolean; upstream: string | null; ahead: number; behind: number; 
/**
 * Richer reading of the same relationship; prefer this over the raw counts.
 */
sync: SyncState; 
/**
 * Commit time of the branch tip, seconds since epoch.
 */
time: number | null; 
/**
 * Abbreviated tip sha, for display.
 */
tip: string | null }
export type BranchList = { local: BranchInfo[]; remote: string[] }
/**
 * How two arbitrary refs relate: commits `ours` has that `theirs` doesn't
 * (ahead) and commits `theirs` has that `ours` doesn't (behind).
 */
export type BranchRelation = { ahead: number; behind: number }
/**
 * What to do with uncommitted changes when switching branches.
 */
export type BranchSwitchMode = 
/**
 * Stash before switching, reapply after. A conflicting reapply leaves the
 * stash intact as a backup. Most protective; the default.
 */
"auto_stash" | 
/**
 * Plain `git checkout`: carry changes to the new branch, but refuse the
 * switch if any change would be overwritten.
 */
"carry" | 
/**
 * Refuse to switch while the working tree is dirty.
 */
"refuse"
export type BuildInfo = { version: string; build_date: string; git_hash: string; debug: boolean }
export type CatalogModel = { id: string; name: string; 
/**
 * Whether the account can actually select this model. Always true for static
 * catalog entries; a live Copilot list marks plan-gated models false so the
 * picker can show them greyed out instead of hiding them.
 */
enabled: boolean }
export type CatalogProvider = { id: string; name: string; base_url: string; dialect: Dialect; models: CatalogModel[] }
/**
 * Where commit change size appears in the graph.
 */
export type ChangeSizeDisplay = 
/**
 * A compact Changes column beside the author.
 */
"column" | 
/**
 * A second line below each commit message.
 */
"row"
/**
 * What happened to uncommitted changes during a branch switch.
 */
export type CheckoutOutcome = 
/**
 * Tree was clean, or changes carried over cleanly. Nothing to report.
 */
"clean" | 
/**
 * Changes were stashed and popped back successfully.
 */
"stashed" | 
/**
 * Changes were stashed, the switch happened, but the pop conflicted. The
 * stash was KEPT as a backup; the working tree has conflict markers.
 */
"stash_pop_conflict"
/**
 * Commit-graph column layout. Column ids are validated on the frontend, so
 * unknown values here are ignored rather than rejected.
 */
export type ColumnLayout = { 
/**
 * Column ids in display order.
 */
order?: string[]; 
/**
 * Column ids the user has hidden.
 */
hidden?: string[]; 
/**
 * Saved widths in logical pixels, keyed by column id.
 */
widths?: Partial<{ [key in string]: number }> }
export type CommitDetail = { sha: string; summary: string; body: string; author_name: string; author_email: string; time: number; parent_shas: string[]; files: FileChange[] }
export type CommitEntry = { sha: string; short_sha: string; summary: string; 
/**
 * Number of files changed compared with the first parent.
 */
files_changed: number; 
/**
 * Lines added compared with the first parent.
 */
additions: number; 
/**
 * Lines removed compared with the first parent.
 */
deletions: number; author_name: string; author_email: string; author_initials: string; 
/**
 * Unix epoch seconds.
 */
time: number; lane: number; 
/**
 * Lane of each parent edge, aligned with `parent_shas`.
 */
parent_lanes: number[]; parent_shas: string[]; is_merge: boolean; refs: RefInfo[] }
/**
 * The three sides of a conflicted file, as full text.
 */
export type ConflictContent = { path: string; 
/**
 * Common ancestor version (stage 1); empty if added on both sides.
 */
base: string; 
/**
 * Our version (stage 2, current branch).
 */
ours: string; 
/**
 * Their version (stage 3, incoming branch).
 */
theirs: string; 
/**
 * Working-tree text with conflict markers, for manual editing.
 */
merged: string; 
/**
 * Any side is binary/undecodable; only ours/theirs whole-file choice is safe.
 */
binary: boolean; 
/**
 * Our side deleted the file; choosing ours removes it.
 */
ours_deleted: boolean; 
/**
 * Their side deleted the file; choosing theirs removes it.
 */
theirs_deleted: boolean }
export type DeviceCodeInfo = { device_code: string; user_code: string; verification_uri: string; 
/**
 * Minimum seconds between polls.
 */
interval: number }
export type Dialect = "anthropic" | "open_ai"
export type DiffLineEntry = { 
/**
 * "+" added, "-" removed, "" context, "@" hunk header.
 */
sign: string; old_no: number | null; new_no: number | null; text: string; 
/**
 * Index into `FileDiff.hunks` this line belongs to. Hunk-header lines
 * (`sign == "@"`) also carry the index of the hunk they introduce.
 */
hunk_index: number }
export type DiffSource = { kind: "staged" } | { kind: "unstaged" } | { kind: "commit"; sha: string }
export type FileChange = { path: string; status: StatusCode; additions: number; deletions: number; conflicted: boolean; 
/**
 * Set when this path is a submodule whose pinned commit moved. Ordinary file
 * actions (stash, discard-by-checkout) can't touch it; the UI must offer
 * submodule-specific handling instead.
 */
submodule: SubmoduleMove | null }
export type FileDiff = { path: string; 
/**
 * Rename source path, when the delta is a rename.
 */
old_path: string | null; additions: number; deletions: number; hunks: HunkHeader[]; lines: DiffLineEntry[]; binary: boolean }
export type GeneratedCommitMessage = { summary: string; description: string }
export type GitProgressPayload = { repo_id: string; operation: string; line: string }
export type GithubComment = { author: string; author_is_bot: boolean; body: string; created_at: string }
export type GithubRepoRef = { owner: string; repo: string }
/**
 * A `@@ -old_start,old_lines +new_start,new_lines @@` hunk boundary.
 */
export type HunkHeader = { old_start: number; old_lines: number; new_start: number; new_lines: number; 
/**
 * Raw header text including any trailing section context.
 */
header: string }
/**
 * What happened when a pattern was added, so the UI can say something true
 * rather than always claiming a line was written.
 */
export type IgnoreOutcome = "added" | "already_present"
export type IssueDetail = { number: number; title: string; body: string; author: string; state: string; labels: string[]; assignee: string | null; comments: GithubComment[]; html_url: string; created_at: string; updated_at: string }
export type IssueSummary = { number: number; title: string; author: string; labels: string[]; assignee: string | null; comments: number; updated_at: string; html_url: string }
export type LogPage = { commits: CommitEntry[]; has_more: boolean }
/**
 * What a merge of a given ref into HEAD would do, without performing it.
 */
export type MergeAnalysis = { 
/**
 * HEAD already contains the target; merging is a no-op.
 */
up_to_date: boolean; 
/**
 * Merge can fast-forward (no merge commit needed).
 */
can_fast_forward: boolean; 
/**
 * A real merge commit would be created.
 */
normal: boolean; 
/**
 * Short sha the target ref resolves to.
 */
target_sha: string }
export type MergeMethod = "merge" | "squash" | "rebase"
/**
 * Outcome of starting a merge.
 */
export type MergeResult = { 
/**
 * HEAD already contained the target; nothing changed.
 */
up_to_date: boolean; 
/**
 * HEAD was advanced without a merge commit.
 */
fast_forwarded: boolean; 
/**
 * Paths left in a conflicted state, needing resolution.
 */
conflicts: string[] }
/**
 * Current in-progress operation state of the repo (merge or cherry-pick).
 */
export type MergeState = { 
/**
 * True when an operation is underway (a merge or cherry-pick is in progress).
 */
merging: boolean; 
/**
 * Which operation is in progress, if any.
 */
operation: OperationKind | null; 
/**
 * Branch/ref/commit being merged or picked, best-effort from the state files.
 */
incoming_label: string | null; 
/**
 * Full prepared commit message (MERGE_MSG), used when finishing the
 * operation so multi-line messages survive intact. None during a rebase.
 */
full_message: string | null; 
/**
 * Paths still conflicted.
 */
conflicts: string[] }
/**
 * A pending index-level operation that can leave conflicts to resolve.
 */
export type OperationKind = "Merge" | "CherryPick" | "Revert" | "Rebase"
export type PollResult = 
/**
 * Token acquired and saved; sign-in is complete.
 */
{ status: "complete" } | 
/**
 * User has not finished authorizing yet; poll again after `interval`.
 */
{ status: "pending"; interval: number }
export type PrDetail = { number: number; title: string; body: string; author: string; author_is_bot: boolean; state: string; draft: boolean; merged: boolean; mergeable: boolean | null; head_ref: string; base_ref: string; additions: number; deletions: number; changed_files: number; comments: GithubComment[]; html_url: string; created_at: string; updated_at: string }
export type PrSummary = { number: number; title: string; author: string; author_is_bot: boolean; draft: boolean; head_ref: string; base_ref: string; updated_at: string; html_url: string }
/**
 * Outcome of a pull, measured the same way as `PushResult`.
 */
export type PullResult = { branch: string | null; upstream: string | null; 
/**
 * Commits brought in from the remote. Zero means there was nothing new.
 */
received: number; 
/**
 * The pull left the branch with commits still to push.
 */
ahead_after: number }
/**
 * Outcome of a push. Measured from the branch's ahead/behind against its
 * upstream before and after, so the report reflects what actually moved rather
 * than what git printed.
 */
export type PushResult = { 
/**
 * The branch that was pushed, if HEAD was on one.
 */
branch: string | null; 
/**
 * Its upstream, e.g. `origin/main`.
 */
upstream: string | null; 
/**
 * Commits handed to the remote. Zero means the remote already matched.
 */
pushed: number }
/**
 * Outcome of a rebase. A clean rebase returns no conflicts; a paused rebase
 * (conflicts to resolve) lists the conflicted paths and leaves the repo in its
 * rebase-in-progress state.
 */
export type RebaseResult = { 
/**
 * Paths left in a conflicted state; the rebase is paused until resolved.
 */
conflicts: string[] }
export type RecentRepo = { name: string; path: string }
export type RefInfo = { name: string; type: RefKind }
export type RefKind = "head" | "branch" | "remote" | "tag"
/**
 * Where a branch ref pointed before an operation, so it can be undone.
 */
export type RefMove = { 
/**
 * The branch that moved.
 */
branch: string; 
/**
 * Full sha the branch pointed at before the move.
 */
previous_sha: string }
/**
 * How a remote-tracking branch relates to the local repo. This is what makes a
 * remote branch legible without checking it out.
 */
export type RemoteBranchInfo = { 
/**
 * Short name, `<remote>/` prefix stripped: `main`, `claude/foo`.
 */
name: string; 
/**
 * Abbreviated tip sha.
 */
tip: string | null; 
/**
 * Commit time of the tip, seconds since epoch.
 */
time: number | null; 
/**
 * Summary line of the tip commit.
 */
summary: string | null; 
/**
 * Name of the local branch this was compared against, when one exists.
 */
local_counterpart: string | null; 
/**
 * Commits this remote branch has that the local counterpart lacks.
 * Zero when there is no same-named local branch to compare with.
 */
ahead_of_local: number; 
/**
 * Commits the local counterpart has that this remote branch lacks.
 */
behind_local: number; 
/**
 * True when no local branch of this name exists - work that is not on this
 * machine in any form.
 */
local_only_missing: boolean }
/**
 * A configured remote and the remote-tracking branches under it.
 */
export type RemoteInfo = { name: string; url: string; 
/**
 * Push URL when it differs from the fetch URL, else None.
 */
push_url: string | null; 
/**
 * Branches under this remote, with sync detail relative to the local repo.
 * Names have the `<remote>/` prefix stripped. Excludes the symbolic HEAD ref.
 */
branches: RemoteBranchInfo[]; 
/**
 * How many of `branches` have no local counterpart at all.
 */
missing_locally: number }
/**
 * A tag on a remote, as reported by `git ls-remote --tags`.
 */
export type RemoteTagInfo = { name: string; 
/**
 * The object the remote's ref points at. For an annotated tag this is the
 * tag object, not the commit, so it need not match `TagInfo::target_sha`.
 */
sha: string }
export type RepoChangedPayload = { repo_id: string }
export type RepoIcon = { source_path: string; label: string; data_url: string; custom: boolean }
export type RepoInfo = { id: string; name: string; path: string; head_branch: string | null }
/**
 * How far a reset rewinds: ref only, ref+index, or ref+index+working tree.
 */
export type ResetMode = 
/**
 * Move the branch ref only; index and working tree keep the changes.
 */
"Soft" | 
/**
 * Move the ref and reset the index; working tree keeps the changes.
 */
"Mixed" | 
/**
 * Move the ref, index, and working tree. Discards uncommitted work.
 */
"Hard"
export type Resolution = 
/**
 * Keep our side wholesale.
 */
{ kind: "ours" } | 
/**
 * Keep their side wholesale.
 */
{ kind: "theirs" } | 
/**
 * Use the provided, hand-edited text.
 */
{ kind: "manual"; text: string }
export type ScannedRepo = { name: string; path: string; 
/**
 * Current branch parsed from .git/HEAD as text (None when detached/unreadable).
 */
head_branch: string | null }
/**
 * One changed line the caller selected, identified by its diff line numbers.
 * Added lines carry `new_no`; removed lines carry `old_no`.
 */
export type SelectedLine = { hunk_index: number; old_no: number | null; new_no: number | null }
export type Settings = { 
/**
 * Paths of repos open in tabs, in tab order, so they can be reopened on launch.
 */
open_repos?: string[]; 
/**
 * Id of the repo that was active when the app last closed.
 */
active_repo_path?: string | null; recents?: RecentRepo[]; code_folder?: string | null; clone_directory?: string | null; update_channel?: UpdateChannel; branch_switch_mode?: BranchSwitchMode; ai_provider?: string | null; ai_model?: string | null; 
/**
 * Custom system instruction for commit-message generation. None uses the
 * built-in default (see `crate::ai::prompt::DEFAULT_INSTRUCTION`).
 */
ai_instruction?: string | null; 
/**
 * Commit-graph column order and visibility.
 */
column_layout?: ColumnLayout | null; 
/**
 * Saved width of the branches and tags pane in logical pixels.
 */
left_panel_width?: number; 
/**
 * Saved width of the changes and commit pane in logical pixels.
 */
right_panel_width?: number; 
/**
 * Whether change size appears below the message or in its own column.
 */
change_size_display?: ChangeSizeDisplay; 
/**
 * Show the change-size indicator in the commit graph.
 */
show_change_indicator?: boolean; 
/**
 * Show exact added and removed line counts beside the size bar.
 */
show_change_line_counts?: boolean; 
/**
 * Default action for the commit button: "commit" or "commit_push". None
 * falls back to plain commit. Validated on the frontend.
 */
commit_button_mode?: string | null; 
/**
 * Show worktree actions and the worktree sidebar section. Off by default;
 * the frontend auto-enables it when a repo already has extra worktrees.
 */
enable_worktrees?: boolean; 
/**
 * Whole-app zoom factor (1.0 = 100%). None uses the default of 1.0.
 * Clamped on the frontend before display.
 */
ui_scale?: number | null; 
/**
 * Custom tab names, keyed by repo path. Absent paths use the repo folder name.
 */
tab_aliases?: Partial<{ [key in string]: string }>; 
/**
 * Show repository favicon or logo images in repository tabs.
 */
show_repo_icons?: boolean; 
/**
 * Hide repository names until the user points at a tab.
 */
tab_icon_only?: boolean; 
/**
 * Saved width of the vertical repository rail in logical pixels.
 */
vertical_tab_width?: number; 
/**
 * "horizontal" or "vertical". Unknown values fall back to horizontal on
 * the frontend so older and hand-edited settings remain safe.
 */
tab_layout?: string | null; 
/**
 * Open tab groups. These disappear when their last repository is closed.
 */
tab_groups?: TabGroupSetting[]; 
/**
 * The shared order of loose repositories and groups. Group entries use a
 * `group:<id>` marker; every other entry is a repository path.
 */
tab_order?: string[]; 
/**
 * Reusable group snapshots shown in Open a repository > Groups.
 */
saved_tab_groups?: TabGroupSetting[]; 
/**
 * What to do about local-only tags after a push: "ask", "always", "never".
 * None means ask. Validated on the frontend.
 */
tag_push_default?: string | null; 
/**
 * Whether the New Tag dialog's "send it to the remote" box starts checked.
 */
tag_push_on_create?: boolean }
export type StashInfo = { index: number; 
/**
 * Raw stash message as git stores it, e.g. "On develop: auto-stash before...".
 */
message: string; 
/**
 * Message with git's "On <branch>: " / "WIP on <branch>: " prefix stripped.
 */
summary: string; 
/**
 * Branch the stash was taken on, parsed from the message when present.
 */
branch: string | null; 
/**
 * Full sha of the stash commit itself.
 */
sha: string; 
/**
 * Full sha of the commit the stash was taken on (first parent); anchors the
 * stash to a row in the graph.
 */
base_sha: string; 
/**
 * Unix epoch seconds of the stash commit.
 */
time: number; files_changed: number; additions: number; deletions: number }
/**
 * Result of a stash-save attempt. A clean working tree is a no-op, not an error.
 */
export type StashOutcome = "stashed" | "nothing_to_stash"
export type StatusCode = "A" | "M" | "D" | "R" | "!"
/**
 * How a submodule's checked-out commit differs from the commit its parent repo
 * pins. `ahead`/`behind` are the workdir commit's position relative to the
 * recorded one.
 */
export type SubmoduleMove = { path: string; 
/**
 * Commit the parent repo records for this submodule.
 */
recorded_sha: string; 
/**
 * Commit the submodule is actually checked out at, if initialized.
 */
workdir_sha: string | null; 
/**
 * Commits the workdir is ahead of the recorded commit.
 */
ahead: number; 
/**
 * Commits the workdir is behind the recorded commit.
 */
behind: number; 
/**
 * False when the submodule has not been checked out (needs init).
 */
initialized: boolean }
/**
 * How a branch stands against the remote. Distinguishes the three cases the
 * old `(0, 0)` collapsed together: genuinely in sync, no upstream configured,
 * and an upstream whose ref could not be resolved.
 */
export type SyncState = 
/**
 * Tracking an upstream, tips match.
 */
{ kind: "in_sync" } | 
/**
 * Tracking an upstream and diverged. At least one of the counts is non-zero.
 */
{ kind: "diverged"; ahead: number; behind: number } | 
/**
 * No upstream configured. The branch has never been pushed anywhere.
 */
{ kind: "never_pushed" } | 
/**
 * An upstream is configured but its ref is missing, e.g. the remote branch
 * was deleted and the stale tracking ref has since been pruned.
 */
{ kind: "upstream_gone" }
/**
 * A named set of repository tabs. Repository paths are stable across app
 * restarts, unlike the in-memory repo ids assigned when a repository opens.
 */
export type TabGroupSetting = { id: string; name: string; color: string; collapsed?: boolean; repo_paths?: string[] }
export type TagInfo = { name: string; 
/**
 * Commit the tag points at, after peeling an annotated tag's wrapper object.
 */
target_sha: string; 
/**
 * Annotated tags carry an author and message; lightweight ones don't.
 */
annotated: boolean }
/**
 * A local tag the given remote does not have, along with whether the remote
 * already holds the commit it points at. Tags on commits the remote lacks
 * cannot be pushed on their own, so they are reported separately.
 */
export type UnpushedTag = { name: string; target_sha: string; 
/**
 * True when the tagged commit is already reachable from a remote-tracking
 * ref, so pushing the tag alone will succeed.
 */
commit_on_remote: boolean }
export type UpdateChannel = "stable" | "beta"
export type WorkingStatus = { staged: FileChange[]; unstaged: FileChange[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
