// @ts-nocheck
// GENERATED by tauri-specta. Do not edit.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async buildInfo() : Promise<BuildInfo> {
    return await TAURI_INVOKE("build_info");
},
/**
 * Returns the current log file contents ("" when it does not exist yet).
 */
async readLog() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Truncates the log file in place so the logger's open handle stays valid.
 */
async clearLog() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_log") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Opens the log directory in the OS file manager.
 */
async openLogsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_logs_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Settings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: Settings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRepo(path: string) : Promise<Result<RepoInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_repo", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeRepo(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_repo", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLog(repoId: string, skip: number, limit: number) : Promise<Result<LogPage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log", { repoId, skip, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getStatus(repoId: string) : Promise<Result<WorkingStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_status", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listBranches(repoId: string) : Promise<Result<BranchList, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_branches", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTags(repoId: string) : Promise<Result<TagInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tags", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listStashes(repoId: string) : Promise<Result<StashInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_stashes", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getFileDiff(repoId: string, path: string, source: DiffSource) : Promise<Result<FileDiff, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_file_diff", { repoId, path, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCommitDetail(repoId: string, sha: string) : Promise<Result<CommitDetail, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_commit_detail", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stageFile(repoId: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stage_file", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unstageFile(repoId: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unstage_file", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stageAll(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stage_all", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unstageAll(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unstage_all", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardFile(repoId: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_file", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Discard every uncommitted change: unstage the index, restore all tracked
 * files to HEAD, and remove untracked files. Irreversible; the caller confirms.
 */
async discardAll(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_all", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCommit(repoId: string, summary: string, description: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_commit", { repoId, summary, description }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkoutBranch(repoId: string, name: string, mode: BranchSwitchMode) : Promise<Result<CheckoutOutcome, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("checkout_branch", { repoId, name, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createBranch(repoId: string, name: string, checkout: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_branch", { repoId, name, checkout }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset the current branch to a commit. Hard reset discards uncommitted work,
 * so it is refused over a dirty tree. Returns where the branch pointed before
 * the reset, so the caller can offer an undo. Soft/Mixed keep the working tree.
 */
async resetCurrent(repoId: string, sha: string, mode: ResetMode) : Promise<Result<RefMove, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_current", { repoId, sha, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Move the current branch ref to a commit without touching the working tree
 * (like `git branch -f <current> <sha>` re-pointing HEAD's branch). Refused
 * over a dirty tree so the tree never silently diverges from the new tip.
 */
async moveCurrentBranch(repoId: string, sha: string) : Promise<Result<RefMove, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_current_branch", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resolve the origin remote's web URL for a commit, or None when it can't be
 * built (no origin, unknown host) or the commit isn't on any remote-tracking
 * branch yet (so the link would 404). Supports GitHub, GitLab, Bitbucket.
 */
async commitWebUrl(repoId: string, sha: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_web_url", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stashSave(repoId: string, message: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stash_save", { repoId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stashPop(repoId: string, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stash_pop", { repoId, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitFetch(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_fetch", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPull(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_pull", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitPush(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_push", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async gitClone(url: string, destination: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("git_clone", { url, destination }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergeAnalysis(repoId: string, reference: string) : Promise<Result<MergeAnalysis, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_analysis", { repoId, reference }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mergeBranch(repoId: string, reference: string) : Promise<Result<MergeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_branch", { repoId, reference }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Merge `source` into `target`, checking out `target` first when it isn't
 * already HEAD. Refuses to switch branches over a dirty tree so no work is
 * lost. This backs the direction modal's reverse ("merge current into other").
 */
async mergeDirectional(repoId: string, target: string, source: string) : Promise<Result<MergeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("merge_directional", { repoId, target, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMergeState(repoId: string) : Promise<Result<MergeState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_merge_state", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async abortMerge(repoId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("abort_merge", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getConflict(repoId: string, path: string) : Promise<Result<ConflictContent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_conflict", { repoId, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveConflict(repoId: string, path: string, resolution: Resolution) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_conflict", { repoId, path, resolution }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async commitMerge(repoId: string, message: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("commit_merge", { repoId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cherry-pick a commit onto the current branch. A clean apply commits
 * immediately (single-parent, keeping the original author) and returns no
 * conflicts. A conflicting apply leaves CHERRY_PICK_HEAD and the conflicted
 * index in place for the operation-aware conflict flow to resolve and finish.
 */
async cherryPick(repoId: string, sha: string) : Promise<Result<MergeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cherry_pick", { repoId, sha }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stageLines(repoId: string, path: string, selection: SelectedLine[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stage_lines", { repoId, path, selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unstageLines(repoId: string, path: string, selection: SelectedLine[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unstage_lines", { repoId, path, selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardLines(repoId: string, path: string, selection: SelectedLine[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_lines", { repoId, path, selection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async scanCodeFolder(folder: string) : Promise<Result<ScannedRepo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_code_folder", { folder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiGetCatalog() : Promise<Result<CatalogProvider[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_get_catalog") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiListConfigured() : Promise<Result<AiProviderStatus[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_list_configured") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiSetApiKey(provider: string, key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_set_api_key", { provider, key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiRemoveProvider(provider: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_remove_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async aiCopilotDeviceStart() : Promise<Result<DeviceCodeInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_copilot_device_start") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * One poll pass; the frontend loops on Pending so sign-in stays cancellable.
 */
async aiCopilotDevicePoll(deviceCode: string, interval: number) : Promise<Result<PollResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ai_copilot_device_poll", { deviceCode, interval }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async generateCommitMessage(repoId: string, provider: string, model: string) : Promise<Result<GeneratedCommitMessage, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("generate_commit_message", { repoId, provider, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiProviderStatus = { id: string; configured: boolean }
export type BranchInfo = { name: string; is_head: boolean; upstream: string | null; ahead: number; behind: number }
export type BranchList = { local: BranchInfo[]; remote: string[] }
/**
 * What to do with uncommitted changes when switching branches.
 */
export type BranchSwitchMode = 
/**
 * Stash before switching, reapply after. A conflicting reapply leaves the
 * stash intact as a backup. Most protective; the default.
 */
"auto_stash" | 
/**
 * Plain `git checkout`: carry changes to the new branch, but refuse the
 * switch if any change would be overwritten.
 */
"carry" | 
/**
 * Refuse to switch while the working tree is dirty.
 */
"refuse"
export type BuildInfo = { version: string; build_date: string; git_hash: string; debug: boolean }
export type CatalogModel = { id: string; name: string }
export type CatalogProvider = { id: string; name: string; base_url: string; dialect: Dialect; models: CatalogModel[] }
/**
 * What happened to uncommitted changes during a branch switch.
 */
export type CheckoutOutcome = 
/**
 * Tree was clean, or changes carried over cleanly. Nothing to report.
 */
"clean" | 
/**
 * Changes were stashed and popped back successfully.
 */
"stashed" | 
/**
 * Changes were stashed, the switch happened, but the pop conflicted. The
 * stash was KEPT as a backup; the working tree has conflict markers.
 */
"stash_pop_conflict"
export type CommitDetail = { sha: string; summary: string; body: string; author_name: string; author_email: string; time: number; parent_shas: string[]; files: FileChange[] }
export type CommitEntry = { sha: string; short_sha: string; summary: string; author_name: string; author_email: string; author_initials: string; 
/**
 * Unix epoch seconds.
 */
time: number; lane: number; 
/**
 * Lane of each parent edge, aligned with `parent_shas`.
 */
parent_lanes: number[]; parent_shas: string[]; is_merge: boolean; refs: RefInfo[] }
/**
 * The three sides of a conflicted file, as full text.
 */
export type ConflictContent = { path: string; 
/**
 * Common ancestor version (stage 1); empty if added on both sides.
 */
base: string; 
/**
 * Our version (stage 2, current branch).
 */
ours: string; 
/**
 * Their version (stage 3, incoming branch).
 */
theirs: string; 
/**
 * Working-tree text with conflict markers, for manual editing.
 */
merged: string; 
/**
 * Any side is binary/undecodable; only ours/theirs whole-file choice is safe.
 */
binary: boolean }
export type DeviceCodeInfo = { device_code: string; user_code: string; verification_uri: string; 
/**
 * Minimum seconds between polls.
 */
interval: number }
export type Dialect = "anthropic" | "open_ai"
export type DiffLineEntry = { 
/**
 * "+" added, "-" removed, "" context, "@" hunk header.
 */
sign: string; old_no: number | null; new_no: number | null; text: string; 
/**
 * Index into `FileDiff.hunks` this line belongs to. Hunk-header lines
 * (`sign == "@"`) also carry the index of the hunk they introduce.
 */
hunk_index: number }
export type DiffSource = { kind: "staged" } | { kind: "unstaged" } | { kind: "commit"; sha: string }
export type FileChange = { path: string; status: StatusCode; additions: number; deletions: number; conflicted: boolean }
export type FileDiff = { path: string; 
/**
 * Rename source path, when the delta is a rename.
 */
old_path: string | null; additions: number; deletions: number; hunks: HunkHeader[]; lines: DiffLineEntry[]; binary: boolean }
export type GeneratedCommitMessage = { summary: string; description: string }
export type GitProgressPayload = { repo_id: string; operation: string; line: string }
/**
 * A `@@ -old_start,old_lines +new_start,new_lines @@` hunk boundary.
 */
export type HunkHeader = { old_start: number; old_lines: number; new_start: number; new_lines: number; 
/**
 * Raw header text including any trailing section context.
 */
header: string }
export type LogPage = { commits: CommitEntry[]; has_more: boolean }
/**
 * What a merge of a given ref into HEAD would do, without performing it.
 */
export type MergeAnalysis = { 
/**
 * HEAD already contains the target; merging is a no-op.
 */
up_to_date: boolean; 
/**
 * Merge can fast-forward (no merge commit needed).
 */
can_fast_forward: boolean; 
/**
 * A real merge commit would be created.
 */
normal: boolean; 
/**
 * Short sha the target ref resolves to.
 */
target_sha: string }
/**
 * Outcome of starting a merge.
 */
export type MergeResult = { 
/**
 * HEAD already contained the target; nothing changed.
 */
up_to_date: boolean; 
/**
 * HEAD was advanced without a merge commit.
 */
fast_forwarded: boolean; 
/**
 * Paths left in a conflicted state, needing resolution.
 */
conflicts: string[] }
/**
 * Current in-progress operation state of the repo (merge or cherry-pick).
 */
export type MergeState = { 
/**
 * True when an operation is underway (a merge or cherry-pick is in progress).
 */
merging: boolean; 
/**
 * Which operation is in progress, if any.
 */
operation: OperationKind | null; 
/**
 * Branch/ref/commit being merged or picked, best-effort from the state files.
 */
incoming_label: string | null; 
/**
 * Paths still conflicted.
 */
conflicts: string[] }
/**
 * A pending index-level operation that can leave conflicts to resolve.
 */
export type OperationKind = "Merge" | "CherryPick"
export type PollResult = 
/**
 * Token acquired and saved; sign-in is complete.
 */
{ status: "complete" } | 
/**
 * User has not finished authorizing yet; poll again after `interval`.
 */
{ status: "pending"; interval: number }
export type RecentRepo = { name: string; path: string }
export type RefInfo = { name: string; type: RefKind }
export type RefKind = "head" | "branch" | "remote" | "tag"
/**
 * Where a branch ref pointed before an operation, so it can be undone.
 */
export type RefMove = { 
/**
 * The branch that moved.
 */
branch: string; 
/**
 * Full sha the branch pointed at before the move.
 */
previous_sha: string }
export type RepoChangedPayload = { repo_id: string }
export type RepoInfo = { id: string; name: string; path: string; head_branch: string | null }
/**
 * How far a reset rewinds: ref only, ref+index, or ref+index+working tree.
 */
export type ResetMode = 
/**
 * Move the branch ref only; index and working tree keep the changes.
 */
"Soft" | 
/**
 * Move the ref and reset the index; working tree keeps the changes.
 */
"Mixed" | 
/**
 * Move the ref, index, and working tree. Discards uncommitted work.
 */
"Hard"
export type Resolution = 
/**
 * Keep our side wholesale.
 */
{ kind: "ours" } | 
/**
 * Keep their side wholesale.
 */
{ kind: "theirs" } | 
/**
 * Use the provided, hand-edited text.
 */
{ kind: "manual"; text: string }
export type ScannedRepo = { name: string; path: string; 
/**
 * Current branch parsed from .git/HEAD as text (None when detached/unreadable).
 */
head_branch: string | null }
/**
 * One changed line the caller selected, identified by its diff line numbers.
 * Added lines carry `new_no`; removed lines carry `old_no`.
 */
export type SelectedLine = { hunk_index: number; old_no: number | null; new_no: number | null }
export type Settings = { 
/**
 * Paths of repos open in tabs, in tab order, so they can be reopened on launch.
 */
open_repos?: string[]; 
/**
 * Id of the repo that was active when the app last closed.
 */
active_repo_path?: string | null; recents?: RecentRepo[]; code_folder?: string | null; clone_directory?: string | null; update_channel?: UpdateChannel; branch_switch_mode?: BranchSwitchMode; ai_provider?: string | null; ai_model?: string | null }
export type StashInfo = { index: number; message: string }
export type StatusCode = "A" | "M" | "D" | "R" | "!"
export type TagInfo = { name: string }
export type UpdateChannel = "stable" | "beta"
export type WorkingStatus = { staged: FileChange[]; unstaged: FileChange[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
