import { useEffect } from 'react'
import { listen } from '@tauri-apps/api/event'
import { toast } from 'sonner'
import { commands, type SessionSource } from '@/lib/bindings'
import { unwrap } from '@/lib/queryKeys'
import { resolveSourceNav } from '@/lib/agentDeskSourceNav'
import { selectChangeEverywhere } from '@/lib/specSync'
import { useWorkspaceStore } from '@/stores/workspaceStore'
import { useUiStore } from '@/stores/uiStore'
import { log, describeError } from '@/lib/log'

const OPEN_SOURCE_EVENT = 'agent-desk://open-source'

/**
 * Mirrors Rust's `commands::agent_desk::OpenSourceTarget`. Not generated by
 * specta -- an event payload is never a command parameter/return, so the
 * exporter never sees it (same reasoning as `useAgentResultDiff.ts`'s
 * `OpenResultDiffTarget`). Field names/casing kept in sync by hand with the
 * Rust struct's `#[serde(rename_all = "camelCase")]`.
 */
interface OpenSourceTarget {
  repoId: string
  repoPath: string
  source: SessionSource
}

/**
 * Main-window-only listener for `agent-desk://open-source`
 * (`commands::agent_desk::agent_session_open_source`).
 *
 * This is the other half of the "View source" bridge `agentDeskTargets.ts`
 * describes: `SessionSourceBanner`'s button asks the backend to focus THIS
 * window and emit the session's repo and source here, and this hook opens
 * the repo as a tab (mirrors `useAgentResultDiff.ts`'s `openRepo`/`addRepo`
 * dance) and then routes to whichever existing surface already shows that
 * kind of source -- the GitHub context panel, an OpenSpec change selection,
 * or the diff view -- via `resolveSourceNav` (`src/lib/agentDeskSourceNav.ts`).
 *
 * `manual`/`checkFailure` sources resolve to `unreachable`: nothing is
 * opened, and the user is told plainly why rather than seeing the window
 * flash to the front for nothing (Rule #1: every action gives visible
 * feedback).
 *
 * Register this once, only where a main-window instance of `App.tsx`
 * mounts (`AppInner`) -- Agent Desk's own window must never try to open a
 * repo tab into itself, it has none (same guard `useAgentResultDiffListener`
 * documents).
 */
export function useAgentDeskSourceListener() {
  const addRepo = useWorkspaceStore((s) => s.addRepo)
  const setActiveRepo = useWorkspaceStore((s) => s.setActiveRepo)
  const openGithubItem = useUiStore((s) => s.openGithubItem)
  const openDiff = useUiStore((s) => s.openDiff)
  const selectCommit = useUiStore((s) => s.selectCommit)
  const showGraph = useUiStore((s) => s.showGraph)

  useEffect(() => {
    const unlisten = listen<OpenSourceTarget>(OPEN_SOURCE_EVENT, (event) => {
      void (async () => {
        const { repoPath, source } = event.payload
        const action = resolveSourceNav(source)
        if (action.kind === 'unreachable') {
          toast.info(action.reason)
          return
        }

        const result = await commands.openRepo(repoPath)
        if (result.status === 'error') {
          toast.error(`Could not open that repository: ${result.error}`)
          log.warn(`agent desk source: openRepo failed for ${repoPath}: ${result.error}`)
          return
        }
        const repo = unwrap(result)
        addRepo(repo)
        setActiveRepo(repo.id)

        switch (action.kind) {
          case 'github':
            openGithubItem(action.itemKind, action.number)
            break
          case 'openspecChange':
            selectChangeEverywhere(action.changeId)
            break
          case 'commit':
            selectCommit(action.oid)
            showGraph()
            break
          case 'diff':
            if (action.path) {
              openDiff({ path: action.path, source: { kind: 'unstaged' } })
            } else {
              toast.info('This chat has no changed files to show yet.')
            }
            break
        }
      })().catch((e: unknown) => {
        log.error(`agent desk source listener failed: ${describeError(e)}`)
      })
    })
    return () => {
      void unlisten.then((fn) => fn())
    }
  }, [addRepo, setActiveRepo, openGithubItem, openDiff, selectCommit, showGraph])
}
