mod ai;
mod commands;
mod error;
mod git;
mod settings;
mod state;
mod watcher;

pub use error::AppError;
pub use git::graph as git_graph;

use state::RepoManager;
use watcher::WatcherRegistry;

fn specta_builder() -> tauri_specta::Builder<tauri::Wry> {
  tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
    commands::app::build_info,
    commands::app::read_log,
    commands::app::clear_log,
    commands::app::open_logs_folder,
    settings::get_settings,
    settings::save_settings,
    commands::repo::open_repo,
    commands::repo::close_repo,
    commands::repo::git_available,
    commands::log::get_log,
    commands::status::get_status,
    commands::branch::list_branches,
    commands::branch::list_tags,
    commands::stash::list_stashes,
    commands::diff::get_file_diff,
    commands::diff::get_commit_detail,
    commands::staging::stage_file,
    commands::staging::unstage_file,
    commands::staging::stage_all,
    commands::staging::unstage_all,
    commands::staging::discard_file,
    commands::commit::create_commit,
    commands::branch::checkout_branch,
    commands::branch::create_branch,
    commands::stash::stash_save,
    commands::stash::stash_pop,
    commands::remote::git_fetch,
    commands::remote::git_pull,
    commands::remote::git_push,
    commands::remote::git_clone,
    commands::merge::merge_analysis,
    commands::merge::merge_branch,
    commands::merge::get_merge_state,
    commands::merge::abort_merge,
    commands::merge::get_conflict,
    commands::merge::resolve_conflict,
    commands::merge::commit_merge,
    commands::patch::stage_lines,
    commands::patch::unstage_lines,
    commands::patch::discard_lines,
    commands::scan::scan_code_folder,
    commands::ai::ai_get_catalog,
    commands::ai::ai_list_configured,
    commands::ai::ai_set_api_key,
    commands::ai::ai_remove_provider,
    commands::ai::ai_copilot_device_start,
    commands::ai::ai_copilot_device_poll,
    commands::ai::generate_commit_message,
  ])
  .typ::<watcher::RepoChangedPayload>()
  .typ::<commands::remote::GitProgressPayload>()
}

pub fn run() {
  let builder = specta_builder();

  #[cfg(debug_assertions)]
  builder
    .export(
      specta_typescript::Typescript::default()
        .header("// @ts-nocheck\n// GENERATED by tauri-specta. Do not edit.\n"),
      "../src/lib/bindings.ts",
    )
    .expect("failed to export typescript bindings");

  tauri::Builder::default()
    .plugin(
      tauri_plugin_log::Builder::new()
        .targets([
          tauri_plugin_log::Target::new(tauri_plugin_log::TargetKind::Stdout),
          tauri_plugin_log::Target::new(tauri_plugin_log::TargetKind::LogDir {
            file_name: Some(commands::app::LOG_FILE_NAME.into()),
          }),
        ])
        .level(if cfg!(debug_assertions) {
          log::LevelFilter::Debug
        } else {
          log::LevelFilter::Info
        })
        .max_file_size(5_000_000)
        .rotation_strategy(tauri_plugin_log::RotationStrategy::KeepSome(5))
        .timezone_strategy(tauri_plugin_log::TimezoneStrategy::UseLocal)
        .build(),
    )
    .plugin(tauri_plugin_dialog::init())
    .plugin(tauri_plugin_opener::init())
    .plugin(tauri_plugin_process::init())
    .plugin(tauri_plugin_updater::Builder::new().build())
    .manage(RepoManager::default())
    .manage(WatcherRegistry::default())
    .invoke_handler(builder.invoke_handler())
    .run(tauri::generate_context!())
    .expect("error while running tauri application");
}
